-- Flores da Terra — Plano de Separação
-- Um registro por variedade em cada semana, planejado em cestos.

CREATE TABLE IF NOT EXISTS public.plano_separacao (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  semana integer NOT NULL CHECK (semana BETWEEN 1 AND 53),
  ano integer NOT NULL CHECK (ano >= 2020),
  variedade text NOT NULL,
  cestos_oferta integer NOT NULL DEFAULT 0 CHECK (cestos_oferta >= 0),
  cestos_mercado integer NOT NULL DEFAULT 0 CHECK (cestos_mercado >= 0),
  cestos_barracao integer NOT NULL DEFAULT 0 CHECK (cestos_barracao >= 0),
  observacao text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT plano_separacao_semana_variedade_unica UNIQUE (semana, ano, variedade)
);

ALTER TABLE public.plano_separacao ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Equipe pode consultar plano de separação" ON public.plano_separacao;
DROP POLICY IF EXISTS "Equipe pode criar plano de separação" ON public.plano_separacao;
DROP POLICY IF EXISTS "Equipe pode atualizar plano de separação" ON public.plano_separacao;
DROP POLICY IF EXISTS "Equipe pode excluir plano de separação" ON public.plano_separacao;

CREATE POLICY "Equipe pode consultar plano de separação"
ON public.plano_separacao FOR SELECT TO anon, authenticated USING (true);

CREATE POLICY "Equipe pode criar plano de separação"
ON public.plano_separacao FOR INSERT TO anon, authenticated WITH CHECK (true);

CREATE POLICY "Equipe pode atualizar plano de separação"
ON public.plano_separacao FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Equipe pode excluir plano de separação"
ON public.plano_separacao FOR DELETE TO anon, authenticated USING (true);

CREATE OR REPLACE FUNCTION public.atualizar_data_plano_separacao()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_atualizar_data_plano_separacao ON public.plano_separacao;

CREATE TRIGGER trg_atualizar_data_plano_separacao
BEFORE UPDATE ON public.plano_separacao
FOR EACH ROW
EXECUTE FUNCTION public.atualizar_data_plano_separacao();

-- Conferência opcional:
-- SELECT * FROM public.plano_separacao ORDER BY ano DESC, semana DESC, variedade;
