-- Flores da Terra — Colhido × Recebido
-- Uma conferência por dia, somente para cestos de crisântemos.

CREATE TABLE IF NOT EXISTS public.conferencia_colhido_recebido (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data_conferencia date NOT NULL UNIQUE,
  recebido_oferta integer NOT NULL DEFAULT 0 CHECK (recebido_oferta >= 0),
  recebido_mercado integer NOT NULL DEFAULT 0 CHECK (recebido_mercado >= 0),
  recebido_barracao integer NOT NULL DEFAULT 0 CHECK (recebido_barracao >= 0),
  observacao text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Permite que a equipe use a tela no aplicativo, como nas demais tabelas do projeto.
ALTER TABLE public.conferencia_colhido_recebido ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Equipe pode consultar conferências" ON public.conferencia_colhido_recebido;
DROP POLICY IF EXISTS "Equipe pode criar conferências" ON public.conferencia_colhido_recebido;
DROP POLICY IF EXISTS "Equipe pode atualizar conferências" ON public.conferencia_colhido_recebido;

CREATE POLICY "Equipe pode consultar conferências"
ON public.conferencia_colhido_recebido
FOR SELECT
TO anon, authenticated
USING (true);

CREATE POLICY "Equipe pode criar conferências"
ON public.conferencia_colhido_recebido
FOR INSERT
TO anon, authenticated
WITH CHECK (true);

CREATE POLICY "Equipe pode atualizar conferências"
ON public.conferencia_colhido_recebido
FOR UPDATE
TO anon, authenticated
USING (true)
WITH CHECK (true);

-- Atualiza automaticamente a data/hora de edição.
CREATE OR REPLACE FUNCTION public.atualizar_data_conferencia_colhido_recebido()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_atualizar_data_conferencia_colhido_recebido
ON public.conferencia_colhido_recebido;

CREATE TRIGGER trg_atualizar_data_conferencia_colhido_recebido
BEFORE UPDATE ON public.conferencia_colhido_recebido
FOR EACH ROW
EXECUTE FUNCTION public.atualizar_data_conferencia_colhido_recebido();

-- Conferência opcional:
-- SELECT * FROM public.conferencia_colhido_recebido ORDER BY data_conferencia DESC;
